# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Run-for-Water-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Run-for-Water-iOS
  
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'FirebaseUI'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod 'TwitterKit'

  target 'Run-for-Water-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Run-for-Water-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
